#pragma once

#define HID_USAGE_PAGE_VENDOR_DEFINED(LO)		(HID_USAGE_PAGE_VENDOR_DEFINED_BEGIN+(LO))
//
// Digitizer Page (0x0D)
//
#define HID_USAGE_DIGITIZER_DIGITIZER			((USAGE)0x01)
#define HID_USAGE_DIGITIZER_TOUCH_SCREEN		((USAGE)0x04)
#define HID_USAGE_DIGITIZER_STYLUS              ((USAGE)0x20)
#define HID_USAGE_DIGITIZER_FINGER              ((USAGE)0x22)
#define HID_USAGE_DIGITIZER_TIP_PRESSURE		((USAGE)0x30)
#define HID_USAGE_DIGITIZER_BATTERY				((USAGE)0x3B)
#define HID_USAGE_DIGITIZER_INVERT				((USAGE)0x3C)
#define HID_USAGE_DIGITIZER_TILT_X				((USAGE)0x3D)
#define HID_USAGE_DIGITIZER_TILT_Y				((USAGE)0x3E)
#define HID_USAGE_DIGITIZER_AZIMUTH				((USAGE)0x3F)
#define HID_USAGE_DIGITIZER_ALTITUDE			((USAGE)0x40)
#define HID_USAGE_DIGITIZER_TWIST				((USAGE)0x41)
#define HID_USAGE_DIGITIZER_ERASER				((USAGE)0x45)
#define HID_USAGE_DIGITIZER_CONFIDENCE			((USAGE)0x47)
#define HID_USAGE_DIGITIZER_2ND_BARREL_SWITCH	((USAGE)0x5A)
#define HID_USAGE_DIGITIZER_STYLUS_SERIAL		((USAGE)0x5B)
